name: Daily Umm Al-Qura Sync

on:
  schedule:
    - cron: '0 22 * * *'  # Every day at 1:00 AM AST (10:00 PM UTC)
  workflow_dispatch:       # Allow manual trigger

jobs:
  run-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests beautifulsoup4 selenium PyGithub

      - name: Run sync script
        run: python sync.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
